from typing import Tuple
from src.schemas.state import PipelineAction, PipelineState

def execute_guardrail_node(state: PipelineState) -> Tuple[bool, str]:
    """
    Deterministically validates the LLM's proposed action against hard business logic.
    Returns (is_valid, validation_error_message).
    """
    action = state.action
    user_data = state.user_data
    
    if not action:
        return False, "No action was generated by the solver."

    # Rule 1: Validate refund amounts
    if action.action_type == "issue_refund":
        if not user_data:
            return False, "Cannot issue a refund without valid user CRM data."
            
        max_allowed_refund = float(user_data.get("amount_paid", 0.0))
        proposed_refund = action.refund_amount
        
        if proposed_refund > max_allowed_refund:
            return False, f"Hallucination detected: Proposed refund (${proposed_refund}) exceeds amount paid (${max_allowed_refund})."
            
        if proposed_refund <= 0:
            return False, "Hallucination detected: Refund action selected but amount is 0 or negative."

    # Rule 2: Non-refund actions should not have a refund amount attached
    if action.action_type in ["escalate_to_human", "reply_only"]:
        if action.refund_amount > 0:
            return False, f"Logic error: Action is '{action.action_type}' but refund amount is ${action.refund_amount}."

    return True, ""